# Generated by Django 3.1.7 on 2021-04-05 22:33

from django.db import migrations, models
import userProfile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=1, upload_to=userProfile.models.uploadTo),
            preserve_default=False,
        ),
    ]
