# Generated by Django 3.1.7 on 2021-04-08 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210408_0400'),
        ('userProfile', '0007_auto_20210408_0358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
