# Generated by Django 3.2 on 2021-04-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210408_0432'),
        ('userProfile', '0011_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart', to='products.Product'),
        ),
        migrations.AddField(
            model_name='profile',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.Product'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wishes',
            field=models.ManyToManyField(blank=True, related_name='wishes', to='products.Product'),
        ),
    ]
