# Generated by Django 3.2 on 2021-04-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0012_auto_20210408_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address1',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='address2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
