# Generated by Django 3.2 on 2021-04-22 00:19

from django.db import migrations, models
import userProfile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0014_auto_20210411_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='/Users/default.jpg', max_length=1000, null=True, upload_to=userProfile.models.uploadTo),
        ),
    ]
