# Generated by Django 3.2 on 2021-04-22 00:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0015_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastLoging',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
