# Generated by Django 3.1.7 on 2021-04-08 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210406_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publishedAt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
