# Generated by Django 3.2 on 2021-04-08 02:32

from django.conf import settings
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='buyers',
        ),
        migrations.AddField(
            model_name='product',
            name='bookers',
            field=models.ManyToManyField(blank=True, related_name='bookers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/Products/default.jpg', upload_to=products.models.uploadTo),
        ),
        migrations.AlterField(
            model_name='product',
            name='lovers',
            field=models.ManyToManyField(blank=True, related_name='lovers', to=settings.AUTH_USER_MODEL),
        ),
    ]
